
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "13008:5678"
    environment:
      # - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      # - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - OLLAMA_URL=http://ollama:8000
    volumes:
      - ./n8n_data:/home/node/.n8n

  ollama:
    image: ollama/ollama
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - ./.ollama:/home/node/.ollama
    ports :
      - :8000

  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

volumes:
  n8n_data:
    external: true

  ollama_data:
    external: true

  qdrant_data:
    external: true

